// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// Sample schema to help you get started.
	/// </summary>
	public partial class User : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""User"",""doc"":""Sample schema to help you get started."",""namespace"":""Avro"",""fields"":[{""name"":""FullName"",""doc"":""The FullName property of type string."",""type"":""string""},{""name"":""FavoriteNumber"",""doc"":""The FavoriteNumber property of type int."",""type"":""int""},{""name"":""FavoriteColor"",""doc"":""he FullName property of type string."",""type"":""string""}]}");
		/// <summary>
		/// The FullName property of type string.
		/// </summary>
		private string _FullName;
		/// <summary>
		/// The FavoriteNumber property of type int.
		/// </summary>
		private int _FavoriteNumber;
		/// <summary>
		/// he FullName property of type string.
		/// </summary>
		private string _FavoriteColor;
		public virtual Schema Schema
		{
			get
			{
				return User._SCHEMA;
			}
		}
		/// <summary>
		/// The FullName property of type string.
		/// </summary>
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				this._FullName = value;
			}
		}
		/// <summary>
		/// The FavoriteNumber property of type int.
		/// </summary>
		public int FavoriteNumber
		{
			get
			{
				return this._FavoriteNumber;
			}
			set
			{
				this._FavoriteNumber = value;
			}
		}
		/// <summary>
		/// he FullName property of type string.
		/// </summary>
		public string FavoriteColor
		{
			get
			{
				return this._FavoriteColor;
			}
			set
			{
				this._FavoriteColor = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.FullName;
			case 1: return this.FavoriteNumber;
			case 2: return this.FavoriteColor;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.FullName = (System.String)fieldValue; break;
			case 1: this.FavoriteNumber = (System.Int32)fieldValue; break;
			case 2: this.FavoriteColor = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
